### ISSUE TITLE
FFMPEG stderr

### ISSUE THREAD

**Issue by Rumczeis** [marcus-j-davies/nvr-js#16]
Hi,

is it possible to see somewhere stderr from ffmpeg or at least the final ffmpeg command  used to capture the camera?

I'm getting an error " - Camera: Domek was terminated, respawning after 10 seconds..." over and over but I'm able to copy stream from camera manually by ffmpeg (e.g.: ffmpeg -i "rtsp://192.168.1.84:5544/live0.264" -c:v copy /mnt/md0/test.mp4) 
So there should be something ffmpeg is complaining about and I need to know what.

Thanks

**Comment by marcus-j-davies** [comment]
Hi @Rumczeis 

try removing `stimeout: '30000000'` from the config, I cant quite re-call, but depending on the ffmpeg version, this command arg, is not implemented / or has been removed (its removed from the config in v3)


the only way currently to monitor stderr from ffmpeg is via  some process monitor

**Comment by Rumczeis** [comment]
Thanks @marcus-j-davies , removing the `stimeout: '30000000'`  and also adding config param: `an: '',` to  `inputConfig` section helped too as the camera was sending incompatible audio codec for mp4 container.
