### ISSUE TITLE
How to add other cameras

### ISSUE THREAD

**Issue by kenyk1972** [marcus-j-davies/nvr-js#17]
Very simple nrv script, good. Don’t know how to add a new camera?
I tried to modify nvrjs.config, but it couldn't start.

**Comment by marcus-j-davies** [comment]
Hello,

As you have not provided the config file, I can only assume you have invalid JSON in the config somewhere
the ID's need to be unique, and each camera is an Object.

```js
cameras: {
  '66e39d21-72c4-405c-a838-05a8e8fe0742': {
    name: 'Camera 1',
    ...
  },
  '03510da7-6543-4ce4-acb7-42e1d675a50c': {
    name: 'Camera 2',
    ...
  }
}
```
