### ISSUE TITLE
disk name invalid, using / as default

### ISSUE THREAD

**Issue by paperjack93** [marcus-j-davies/nvr-js#2]
Hello, I am running this on a raspberry pi and I keep getting message 
"disk name invalid, using / as default"
Any ideas?

**Comment by marcus-j-davies** [comment]
Hello,

**storageVolume** should be the root of a volume, it should not be a sub folder of that Volume.

I.e if I mounted a HD at
**/volumes/CCTV** then that is what you should put. To be fair, it won't cause any issues putting a Subfolder, but the size on the UI won't be correct.

**Comment by paperjack93** [comment]
Hi, I solved this by adding a storageDrive variable that uses the actual drive (for space) and kept the storageVolume as the place where files are saved

**Comment by marcus-j-davies** [comment]
@paperjack93 

Cool!

I'm working on (have almost finished) V2 - which has a much polished UI (the gist of it)
it has some breaking changes (and of course a few fixes) - but keep an eye out.

![image](https://user-images.githubusercontent.com/55892693/147241111-3f8d7120-211e-4570-8608-1a15a2d1292d.png)

**Comment by marcus-j-davies** [comment]
@paperjack93 

It might be worth adding this to your input config also - I will be adding it by default in the example config for V2

`stimeout: '30000000'`

see here:
https://github.com/marcus-j-davies/nvr-js/blob/d120b9901936a249ca9013e3044719c82b69b1cb/nvrjs.config.example.js#L32

I found after 3 days - my cameras stopped producing frames, which caused ffmpeg to halt - this setting allows ffmpeg to restart after an amount of time of no frames being received.
